// js/engine/strategy/hypothesis/observability/verbTables.js
// ============================================================================
// STATIC OBSERVABILITY LEXICAL DATA
//
// Extracted from observability.js. Pure static data only: tiered verb tables
// and derived sets. No classification, mutation, or runtime-state dependency.
// Imported by observability.js; this module must not import the entry module.
// ============================================================================

// ============================================================================
// CONFIGURATION: OBSERVABILITY CORE VERBS
// Organized by semantic class → mapped to observability tier
// ============================================================================

export const OBSERVABILITY_CORE = {
  // ------------------------------------------------------------------------
  // HIGH TIER: Immediately visible, unambiguous physical/expressive signals
  // ------------------------------------------------------------------------
  high: [
    // Physical reactions
    "flinch",
    "recoil",
    "jerk",
    "stagger",
    "stumble",
    "trip",
    "slip",
    "fall",
    "collapse",
    "crumple",
    "slump",
    "sway",
    "tremble",
    "shake",
    "shudder",
    "quiver",
    "vibrate",
    "convulse",
    "spasm",
    "tic",
    "wince",
    "grimace",

    // Facial/visual signals
    "blink",
    "stare",
    "glare",
    "squint",
    "widen",
    "narrow",
    "roll",
    "dart",
    "avert",
    "meet",
    "lock",
    "scan",
    "peer",
    "gaze",
    "ogle",
    "glance",

    // Vocal expressions
    "shout",
    "yell",
    "scream",
    "shriek",
    "bellow",
    "roar",
    "howl",
    "wail",
    "cry",
    "weep",
    "sob",
    "whimper",
    "whine",
    "moan",
    "groan",
    "sigh",
    "gasp",
    "choke",
    "cough",
    "sniff",
    "snort",
    "laugh",
    "chuckle",
    "giggle",
    "snicker",
    "cackle",
    "hiss",
    "spit",
    "snap",
    "growl",
    "snarl",

    // Body movement/posture
    "step",
    "stride",
    "march",
    "stomp",
    "shuffle",
    "creep",
    "sneak",
    "lurk",
    "lean",
    "lurch",
    "pivot",
    "spin",
    "turn",
    "face",
    "avoid",
    "dodge",
    "duck",
    "cower",
    "crouch",
    "kneel",
    "bow",
    "nod",
    "shrug",

    // Emotional leakage
    "blush",
    "flush",
    "blanch",
    "pale",
    "sweat",
    "tear",
    "drool",
    "froth"
  ],

  // ------------------------------------------------------------------------
  // MEDIUM TIER: Context-dependent but inferable from behavior/situation
  // ------------------------------------------------------------------------
  medium: [
    // Subtle physical shifts
    "shift",
    "adjust",
    "settle",
    "fidget",
    "fiddle",
    "twitch",
    "wiggle",
    "tap",
    "drum",
    "click",
    "rustle",
    "scuff",
    "drag",
    "pull",

    // Facial micro-expressions
    "furrow",
    "raise",
    "tighten",
    "relax",
    "pout",
    "pucker",
    "smirk",
    "sneer",
    "scowl",
    "beam",
    "grin",
    "smile",
    "frown",
    "puff",

    // Vocal nuances
    "mutter",
    "mumble",
    "murmur",
    "whisper",
    "drawl",
    "stammer",
    "stutter",
    "falter",
    "trail",
    "pause",
    "halt",
    "stop",
    "start",
    "resume",
    "interrupt",
    "interject",
    "clarify",
    "rephrase",
    "elaborate",
    "summarize",

    // Social/interactive behaviors
    "align",
    "side",
    "oppose",
    "confront",
    "challenge",
    "appease",
    "placate",
    "deflect",
    "evade",
    "confide",
    "disclose",
    "divulge",
    "betray",
    "conceal",
    "withhold",
    "share",
    "offer",
    "grant",
    "deny",
    "refuse",
    "accept",
    "reject",
    "embrace",
    "shun",
    "welcome",
    "dismiss",
    "ignore",

    // Decision/commitment signals
    "commit",
    "decide",
    "resolve",
    "determine",
    "conclude",
    "choose",
    "pick",
    "select",
    "opt",
    "prefer",
    "favor",
    "abandon",
    "adopt",

    // Pacing/rhythm changes
    "accelerate",
    "slow",
    "rush",
    "hurry",
    "dawdle",
    "linger",
    "wait"
  ],

  // ------------------------------------------------------------------------
  // LOW TIER: Borderline/internal but sometimes expressed via secondary cues
  // ------------------------------------------------------------------------
  low: [
    // Cognitive behaviors
    "reflect",
    "ruminate",
    "ponder",
    "contemplate",
    "consider",
    "reconsider",
    "evaluate",
    "analyze",
    "scrutinize",
    "examine",
    "inspect",
    "review",
    "reassess",
    "weigh",
    "measure",
    "gauge",
    "judge",
    "assess",
    "appraise",

    // Internal state verbs
    "doubt",
    "trust",
    "believe",
    "suspect",
    "fear",
    "hope",
    "wish",
    "want",
    "need",
    "crave",
    "desire",
    "loathe",
    "detest",
    "adore",
    "cherish",

    // Abstract behavioral shifts
    "waver",
    "vacillate",
    "oscillate",
    "hesitate",
    "delay",
    "postpone",
    "procrastinate",
    "hasten",
    "expedite",
    "facilitate",
    "hinder",
    "impede"
  ]
};

// ============================================================================
// DERIVED LISTS
// ============================================================================

export const CORE_VERBS_SET = new Set([
  ...OBSERVABILITY_CORE.high,
  ...OBSERVABILITY_CORE.medium,
  ...OBSERVABILITY_CORE.low
]);


export const EXPANDED_OBSERVABLE_VERBS = [
  // Original core
  "hesitate",
  "reveal",
  "withdraw",
  "state",
  "admit",
  "question",
  "overcompensate",
  "seek",
  "retract",
  "paralyze",
  "refuse",
  "defend",
  "explain",
  "doubt",
  "regress",
  "exhaust",
  "collapse",
  "freeze",
  "lash",
  "shut",
  "break",
  "crack",
  "snap",
  "pivot",
  "abandon",
  "initiate",
  "become",
  "stop",
  "start",
  "show",
  "exhibit",
  "demonstrate",
  "display",
  "manifest",
  "express",

  // Cognitive/decision
  "reconsider",
  "rethink",
  "second-guess",
  "waver",
  "vacillate",
  "oscillate",
  "commit",
  "decide",
  "resolve",
  "determine",
  "conclude",

  // Emotional/expressive
  "flinch",
  "recoil",
  "tense",
  "relax",
  "sigh",
  "groan",
  "mutter",
  "whisper",
  "shout",
  "yell",
  "laugh",
  "cry",
  "weep",
  "smile",
  "frown",
  "grimace",
  "wince",
  "blanch",
  "flush",

  // Social/interactive
  "align",
  "side",
  "oppose",
  "confront",
  "challenge",
  "appease",
  "placate",
  "deflect",
  "dodge",
  "evade",
  "confide",
  "disclose",
  "divulge",
  "betray",
  "conceal",
  "withhold",
  "share",
  "offer",

  // Physical/embodied
  "shift",
  "turn",
  "face",
  "avoid",
  "approach",
  "retreat",
  "advance",
  "step",
  "move",
  "pause",
  "halt",
  "grip",
  "clench",
  "release",
  "drop",
  "grab",
  "hold",
  "let",
  "lean",
  "slump",
  "straighten",

  // Verbal/communication
  "stammer",
  "stutter",
  "falter",
  "trail",
  "interrupt",
  "interject",
  "clarify",
  "rephrase",
  "elaborate",
  "summarize",
  "agree",
  "disagree",
  "nod",
  "shake",
  "signal",
  "gesture",
  "point",
  "indicate",

  // Meta-cognitive
  "reflect",
  "ruminate",
  "ponder",
  "contemplate",
  "analyze",
  "scrutinize",
  "examine",
  "inspect",
  "review",
  "reassess",
  "evaluate",
  "weigh",

  // Breakdown/failure
  "stall",
  "lock",
  "short-circuit",
  "malfunction",
  "glitch",
  "stumble",
  "trip",
  "slip",
  "miss",
  "fail",
  "fumble",

  // Intensification/de-escalation
  "escalate",
  "amplify",
  "magnify",
  "heighten",
  "deepen",
  "sharpen",
  "focus",
  "zero",
  "hone",
  "tighten",
  "soften",
  "temper",
  "moderate",
  "qualify",
  "hedge",
  "backpedal",
  "disengage"
];


export const EXPANDED_VERBS_SET = new Set(
  EXPANDED_OBSERVABLE_VERBS.map((verb) => verb.toLowerCase())
);
